-- SmartFlow: Real-time traffic intelligence and predictive analytics platform
-- PostgreSQL/Supabase Schema with PostGIS Geospatial Analytics Support

-- Enable PostGIS extension (required for spatial data types and operations)
CREATE EXTENSION IF NOT EXISTS postgis;

-- Enable UUID-OSSP extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Helper function to automatically update updated_at timestamp columns
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 1. road_segments
-- Represents individual street segments or highway sections mapped from OSM
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS road_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    osm_id BIGINT NOT NULL,
    name VARCHAR(255),
    geometry GEOMETRY(LineString, 4326) NOT NULL,
    speed_limit INTEGER, -- in km/h or mph depending on region config (standard km/h)
    length DOUBLE PRECISION, -- length of the segment in meters
    CONSTRAINT unique_osm_id UNIQUE (osm_id)
);

-- Spatial and standard indexing for road_segments
CREATE INDEX IF NOT EXISTS idx_road_segments_geom ON road_segments USING GiST (geometry);
CREATE INDEX IF NOT EXISTS idx_road_segments_osm_id ON road_segments (osm_id);

-- -----------------------------------------------------------------------------
-- 2. traffic_readings
-- Time-series historical and live telemetry updates for each road segment
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS traffic_readings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    segment_id BIGINT NOT NULL REFERENCES road_segments(id) ON DELETE CASCADE,
    current_speed DOUBLE PRECISION NOT NULL, -- current average speed in km/h
    congestion_score NUMERIC(3, 2) NOT NULL CHECK (congestion_score >= 0.00 AND congestion_score <= 1.00), -- 0 = free flow, 1 = absolute gridlock
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Performance indexing for traffic_readings analytics
CREATE INDEX IF NOT EXISTS idx_traffic_readings_segment_id ON traffic_readings (segment_id);
CREATE INDEX IF NOT EXISTS idx_traffic_readings_timestamp ON traffic_readings (timestamp DESC);
-- Compound index for fast segment-level temporal queries
CREATE INDEX IF NOT EXISTS idx_traffic_readings_seg_time ON traffic_readings (segment_id, timestamp DESC);

-- -----------------------------------------------------------------------------
-- 3. weather_snapshots
-- Environmental conditions tracked spatially to correlate with traffic patterns
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weather_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    geometry GEOMETRY(Point, 4326) NOT NULL,
    temperature DOUBLE PRECISION, -- in Celsius
    rain_intensity DOUBLE PRECISION, -- in mm/hour
    visibility DOUBLE PRECISION, -- in meters
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Spatial and temporal indexing for weather
CREATE INDEX IF NOT EXISTS idx_weather_snapshots_geom ON weather_snapshots USING GiST (geometry);
CREATE INDEX IF NOT EXISTS idx_weather_snapshots_timestamp ON weather_snapshots (timestamp DESC);

-- -----------------------------------------------------------------------------
-- 4. incidents
-- Live road disruptions (accidents, hazards, debris, vehicle breakdown)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS incidents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_type VARCHAR(100) NOT NULL, -- e.g., accident, congestion, debris, vehicle_breakdown
    description TEXT,
    geometry GEOMETRY(Point, 4326) NOT NULL,
    severity VARCHAR(50) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    status VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'resolved', 'cleared')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to keep updated_at automatically updated
CREATE TRIGGER set_timestamp_incidents
    BEFORE UPDATE ON incidents
    FOR EACH ROW
    EXECUTE FUNCTION trigger_set_timestamp();

-- Spatial, categorical, and temporal indexing for incidents
CREATE INDEX IF NOT EXISTS idx_incidents_geom ON incidents USING GiST (geometry);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents (status);
CREATE INDEX IF NOT EXISTS idx_incidents_created_at ON incidents (created_at DESC);

-- -----------------------------------------------------------------------------
-- 5. construction_zones
-- Planned or ongoing construction areas restricting lane flow
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS construction_zones (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    description TEXT,
    geometry GEOMETRY(Geometry, 4326) NOT NULL, -- Supports both LineString and Polygon
    status VARCHAR(50) NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'active', 'completed')),
    start_date DATE NOT NULL,
    end_date DATE,
    CONSTRAINT chk_construction_geom_type CHECK (
        ST_GeometryType(geometry) IN ('ST_LineString', 'ST_Polygon', 'ST_MultiLineString', 'ST_MultiPolygon')
    )
);

-- Spatial and status indexing for construction zones
CREATE INDEX IF NOT EXISTS idx_construction_zones_geom ON construction_zones USING GiST (geometry);
CREATE INDEX IF NOT EXISTS idx_construction_zones_status ON construction_zones (status);
CREATE INDEX IF NOT EXISTS idx_construction_zones_dates ON construction_zones (start_date, end_date);

-- -----------------------------------------------------------------------------
-- 6. predictions
-- Logged ML inference results for routing pairs to measure model drift and quality
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS predictions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    origin_lat DOUBLE PRECISION NOT NULL,
    origin_lng DOUBLE PRECISION NOT NULL,
    dest_lat DOUBLE PRECISION NOT NULL,
    dest_lng DOUBLE PRECISION NOT NULL,
    predicted_time DOUBLE PRECISION NOT NULL, -- predicted travel duration in seconds
    actual_time DOUBLE PRECISION, -- actual travel duration in seconds (completed post-trip)
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexing coordinates (often helpful for quick geographic lookup) and temporal analysis
CREATE INDEX IF NOT EXISTS idx_predictions_timestamp ON predictions (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_predictions_origin ON predictions (origin_lat, origin_lng);
CREATE INDEX IF NOT EXISTS idx_predictions_dest ON predictions (dest_lat, dest_lng);
